// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Return a read-only status snapshot of the tome system.
	 * 
	 *  The single boundary command for this phase. The `app` handle is accepted so
	 *  later phases can inject a [`crate::sink::TauriEventSink`] for long-running
	 *  variants; for the read-only status path it is currently unused.
	 */
	getStatus: () => typedError<StatusReport_Serialize, TomeError>(__TAURI_INVOKE("get_status")),
};

/** Events */
export const events = {
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
/**  A count that may have failed with an error message. */
export type CountOrError = CountOrError_Serialize | CountOrError_Deserialize;

/**  A count that may have failed with an error message. */
export type CountOrError_Deserialize = {
	count: number | null,
	error: string | null,
};

/**  A count that may have failed with an error message. */
export type CountOrError_Serialize = {
	count: number | null,
	error?: string | null,
};

/**
 *  The role a directory plays in the sync pipeline.
 * 
 *  The `clap::ValueEnum` derive lets `tome add --role <ROLE>` accept these
 *  variants in their kebab-case form (matching the `tome.toml` wire format).
 */
export type DirectoryRole = 
/**  Read-only, owned by package manager (e.g. Claude plugins cache) */
"managed" | 
/**  Skills discovered here AND distributed here (bidirectional) */
"synced" | 
/**  Skills discovered here, not distributed here */
"source" | 
/**  Skills distributed here, not discovered here */
"target";

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus = DirectoryStatus_Serialize | DirectoryStatus_Deserialize;

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus_Deserialize = {
	name: string,
	directory_type: string,
	role: DirectoryRole,
	/**
	 *  Human-readable description of the role (e.g. `"Synced (skills
	 *  discovered here AND distributed here)"`). Display-only — GUI
	 *  consumers should branch on [`role`](Self::role) instead.
	 */
	role_description: string,
	path: string,
	/**
	 *  Number of skills discovered (for discovery dirs) or symlinks present (for target dirs),
	 *  or an error message if counting failed.
	 */
	skill_count: CountOrError_Deserialize,
	/**  Warnings emitted during discovery. */
	warnings: string[],
	/**
	 *  True iff `directories.<name>.path` was rewritten by a `machine.toml`
	 *  `[directory_overrides.<name>]` entry during config load (PORT-05).
	 *  JSON consumers can use this to render the same context that text-mode
	 *  `tome status` shows via the `(override)` annotation.
	 */
	override_applied: boolean,
};

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus_Serialize = {
	name: string,
	directory_type: string,
	role: DirectoryRole,
	/**
	 *  Human-readable description of the role (e.g. `"Synced (skills
	 *  discovered here AND distributed here)"`). Display-only — GUI
	 *  consumers should branch on [`role`](Self::role) instead.
	 */
	role_description: string,
	path: string,
	/**
	 *  Number of skills discovered (for discovery dirs) or symlinks present (for target dirs),
	 *  or an error message if counting failed.
	 */
	skill_count: CountOrError_Serialize,
	/**  Warnings emitted during discovery. */
	warnings: string[],
	/**
	 *  True iff `directories.<name>.path` was rewritten by a `machine.toml`
	 *  `[directory_overrides.<name>]` entry during config load (PORT-05).
	 *  JSON consumers can use this to render the same context that text-mode
	 *  `tome status` shows via the `(override)` annotation.
	 */
	override_applied: boolean,
};

/**
 *  Coarse, stable error categories surfaced to the front-end (D-15).
 * 
 *  Grows additively. The GUI branches on this discriminant; new variants are a
 *  non-breaking superset. Mirrors `tome::DomainErrorKind` plus an `Internal`
 *  fallback (the domain enum deliberately omits `Internal` — see its docs).
 */
export type ErrorCode = 
/**  Input/config validation failure. */
"Validation" | 
/**  A required path/config/resource was not found. */
"NotFound" | 
/**  A filesystem operation was denied by the OS. */
"Permission" | 
/**  A content-hash or path-overlap collision. */
"Conflict" | 
/**  A `git` clone/update operation failed. */
"Git" | 
/**  A generic I/O failure. */
"Io" | 
/**  Anything not classified by a domain sentinel (the fallback, D-14). */
"Internal";

/**
 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
 * 
 *  Classification reuses the same content-hash comparison `reconcile.rs`
 *  performs against the marketplace: every lockfile entry must have a
 *  matching manifest entry whose `content_hash` equals the lockfile-recorded
 *  value. Any divergence (missing manifest entry OR hash mismatch) increments
 *  `drift_count`.
 * 
 *  Variant tag style matches the GUI's discriminated-union pattern (D-GUI-08):
 *  the serialized shape is `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`
 *  so the React side can pattern-match without parsing strings.
 */
export type LockfileState = 
/**  Every lockfile entry's `content_hash` matches the manifest. */
{ kind: "in_sync" } | 
/**
 *  At least one lockfile entry has no matching manifest hash. `drift_count`
 *  counts the divergent entries (mismatch + missing manifest combined).
 */
{ kind: "out_of_sync"; drift_count: number } | 
/**  `tome.lock` does not exist on disk (fresh `tome_home`, never synced). */
{ kind: "missing" };

/**
 *  Per-machine prefs summary shown in the Status view (VIEW-01).
 * 
 *  Surfaces the integer counts the Status view's `MACHINE` row renders
 *  ("N skills disabled"). Counts only — the full skill / directory lists
 *  stay in `machine.toml`.
 */
export type MachinePrefsSummary = {
	/**
	 *  `MachinePrefs.disabled.len()` — count of skills globally disabled
	 *  on this machine.
	 */
	disabled_count: number,
	/**
	 *  `MachinePrefs.disabled_directories.len()` — count of directories
	 *  disabled on this machine.
	 */
	disabled_directory_count: number,
};

/**
 *  One row of the Unowned section in `tome status` and `tome doctor`.
 *  Per D-D3 in the Phase 14 CONTEXT.md.
 */
export type SkillSummary = {
	/**  Skill name as displayed. */
	name: string,
	/**
	 *  Last directory that owned this skill, captured at transition time
	 *  (D-C1). `None` for entries that became Unowned before Phase 14
	 *  landed — consumers fall back to `source_path_display` (D-C2).
	 */
	previous_source: string | null,
	/**
	 *  `paths::collapse_home`-rendered `source_path` from the manifest.
	 *  Always populated; serves as the D-C2 fallback when
	 *  `previous_source` is `None`, and as supplementary info otherwise.
	 */
	source_path_display: string,
	/**
	 *  ISO 8601 timestamp from the manifest (preserved across Owned→Unowned
	 *  transition per Phase 11 manifest semantics).
	 */
	synced_at: string,
	/**
	 *  Mirrors `SkillEntry::managed`. Display-only; consumers may want
	 *  to surface "originally a managed plugin" for context.
	 */
	managed: boolean,
};

/**  Complete status report for the tome system. */
export type StatusReport = StatusReport_Serialize | StatusReport_Deserialize;

/**  Complete status report for the tome system. */
export type StatusReport_Deserialize = {
	configured: boolean,
	library_dir: string,
	/**  Number of skills consolidated in the library, or an error message. */
	library_count: CountOrError_Deserialize,
	/**
	 *  RFC-3339 timestamp of last successful sync; `null` if never synced
	 *  or pre-v0.11 manifest. Per D-LSYNC-2 (OBS-07): "never" in text;
	 *  `null` in JSON. No `skip_serializing_if` — emit `"last_sync": null`
	 *  for stable-shape JSON consumers (matches `unowned: []` pattern).
	 */
	last_sync: string | null,
	directories: DirectoryStatus_Deserialize[],
	/**
	 *  Skills in the library whose source was removed from `tome.toml`
	 *  (Unowned per LIB-04). Surfaces in text rendering between the
	 *  Directories table and the Health line (D-D2). Always present in
	 *  JSON output for stable shape; empty array when no Unowned skills.
	 */
	unowned: SkillSummary[],
	/**
	 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
	 *  Surfaces in the Status view's `LOCKFILE` row paired with `StatusDot`.
	 *  JSON shape: `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`.
	 */
	lockfile: LockfileState,
	/**
	 *  Per-machine prefs summary (VIEW-01). Surfaces in the Status view's
	 *  `MACHINE` row ("N skills disabled").
	 */
	machine_prefs_summary: MachinePrefsSummary,
	/**  Number of health issues, or an error message. */
	health: CountOrError_Deserialize,
};

/**  Complete status report for the tome system. */
export type StatusReport_Serialize = {
	configured: boolean,
	library_dir: string,
	/**  Number of skills consolidated in the library, or an error message. */
	library_count: CountOrError_Serialize,
	/**
	 *  RFC-3339 timestamp of last successful sync; `null` if never synced
	 *  or pre-v0.11 manifest. Per D-LSYNC-2 (OBS-07): "never" in text;
	 *  `null` in JSON. No `skip_serializing_if` — emit `"last_sync": null`
	 *  for stable-shape JSON consumers (matches `unowned: []` pattern).
	 */
	last_sync: string | null,
	directories: DirectoryStatus_Serialize[],
	/**
	 *  Skills in the library whose source was removed from `tome.toml`
	 *  (Unowned per LIB-04). Surfaces in text rendering between the
	 *  Directories table and the Health line (D-D2). Always present in
	 *  JSON output for stable shape; empty array when no Unowned skills.
	 */
	unowned: SkillSummary[],
	/**
	 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
	 *  Surfaces in the Status view's `LOCKFILE` row paired with `StatusDot`.
	 *  JSON shape: `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`.
	 */
	lockfile: LockfileState,
	/**
	 *  Per-machine prefs summary (VIEW-01). Surfaces in the Status view's
	 *  `MACHINE` row ("N skills disabled").
	 */
	machine_prefs_summary: MachinePrefsSummary,
	/**  Number of health issues, or an error message. */
	health: CountOrError_Serialize,
};

/**
 *  Front-end progress event streamed to the webview.
 * 
 *  Carries the **typed** [`SyncStage`] enum directly (not a stringified label)
 *  so the front-end can pattern-match the stage — WARNING 4's typed option.
 *  `SyncStage` already derives gated `specta::Type` and is `Copy` (25-02), so
 *  it crosses the boundary as a TS string-union discriminant.
 */
export type SyncProgress = {
	/**  Which pipeline stage this event refers to. */
	stage: SyncStage,
	/**  Units processed so far in this stage (0 when not applicable). */
	current: number,
	/**  Total units in this stage (0 when unknown / not applicable). */
	total: number,
};

/**
 *  The pipeline stage a [`ProgressEvent`] refers to.
 * 
 *  Mirrors the six stages of the `sync` pipeline (see the crate-level docs):
 *  Reconcile → Discover → Consolidate → Distribute → Cleanup → Save. Kept as a
 *  typed enum (not a `&str`) so the GUI exhaustively matches stages (D-10).
 */
export type SyncStage = 
/**  Lockfile-authoritative drift detection for managed skills. */
"Reconcile" | 
/**  Scan configured directories for `*\/SKILL.md` directories. */
"Discover" | 
/**  Copy discovered skills into the library (library-canonical model). */
"Consolidate" | 
/**  Push library skills to target tools via symlinks. */
"Distribute" | 
/**  Three-bucket stale-skill report + orphan transitions. */
"Cleanup" | 
/**  Persist manifest, lockfile, and `.gitignore`. */
"Save";

/**
 *  The structured error payload that crosses the Tauri IPC boundary (D-16).
 * 
 *  - `code`: the stable [`ErrorCode`] the GUI pattern-matches on.
 *  - `message`: the top-level error string (`err.to_string()`).
 *  - `context`: the flattened anyhow cause chain, outermost first — the same
 *    information the CLI prints via `{e:#}`, available for a details view.
 */
export type TomeError = {
	/**  Stable, coarse classification. */
	code: ErrorCode,
	/**  Top-level human-readable message. */
	message: string,
	/**  Flattened anyhow `.context()` chain (outermost first). */
	context: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

