// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Return a read-only status snapshot of the tome system.
	 * 
	 *  The single boundary command for this phase. The `app` handle is accepted so
	 *  later phases can inject a [`crate::sink::TauriEventSink`] for long-running
	 *  variants; for the read-only status path it is currently unused.
	 */
	getStatus: () => typedError<StatusReport_Serialize, TomeError>(__TAURI_INVOKE("get_status")),
	/**
	 *  Return the discovered skill list backing the GUI's VIEW-02 (Skills view).
	 * 
	 *  Thin wrapper over [`tome::list::collect`] — the CORE-01 collect-shape
	 *  function. The GUI fetches once on mount, then runs fuzzy filter / sort /
	 *  group-by JS-side (RESEARCH §"Standard Stack — Fuzzy search"); per-keystroke
	 *  IPC would blow the 60fps budget.
	 */
	listSkills: () => typedError<ListReport, TomeError>(__TAURI_INVOKE("list_skills")),
	/**
	 *  Aggregate a single skill's right-pane payload for the GUI's
	 *  `DetailHeader` + `MarkdownBody` (Phase 26 plan 26-03 / VIEW-03 / D-05).
	 * 
	 *  Wraps [`tome::skill::collect_detail`] — manifest entry + parsed
	 *  frontmatter projection + machine-prefs disabled flag + capped markdown
	 *  body. Body length is capped at 1 MiB at the domain layer so the webview
	 *  render path is bounded.
	 */
	getSkillDetail: (name: SkillName) => typedError<SkillDetail, TomeError>(__TAURI_INVOKE("get_skill_detail", { name })),
	/**
	 *  Toggle a skill's membership in the global `disabled` set in `machine.toml`
	 *  (Phase 26 plan 26-03 / D-06 — the lone Phase 26 mutation).
	 * 
	 *  Routes through the shared [`tome::actions::set_skill_disabled`] helper, so
	 *  the GUI and the browse TUI hit the same atomic temp+rename. The Phase-26
	 *  file watcher (plan 26-06) fires `MachinePrefsChanged` for the resulting
	 *  write — own-process writes are observed verbatim, no manual refresh
	 *  signal needed.
	 */
	setSkillDisabled: (name: SkillName, disabled: boolean) => typedError<null, TomeError>(__TAURI_INVOKE("set_skill_disabled", { name, disabled })),
	/**
	 *  Reveal the resolved source folder of a skill in Finder (Phase 26 plan
	 *  26-03 / D-07).
	 * 
	 *  Resolves the source path through [`tome::actions::resolve_source_path`]
	 *  (Owned manifest source / Unowned library-canonical fallback), then asks
	 *  `tauri-plugin-opener` to do the OS-call. The plugin maps to `open -R` on
	 *  macOS, `xdg-open` parents on Linux, `explorer.exe /select,` on Windows.
	 */
	openSourceFolder: (name: SkillName) => typedError<null, TomeError>(__TAURI_INVOKE("open_source_folder", { name })),
	/**
	 *  Return the resolved source path of a skill as a UTF-8 string (Phase 26
	 *  plan 26-03 / D-07).
	 * 
	 *  The Rust side resolves the path; the React side calls
	 *  `@tauri-apps/plugin-clipboard-manager::writeText` with the returned
	 *  string. Splitting the work this way keeps the IPC contract narrow (a
	 *  single `String` return type; no clipboard-write plumbing crossing the
	 *  boundary).
	 */
	copyPath: (name: SkillName) => typedError<string, TomeError>(__TAURI_INVOKE("copy_path", { name })),
	/**
	 *  Return the full doctor report for the GUI Health view (Phase 26 plan
	 *  26-05 / VIEW-05).
	 * 
	 *  Wraps [`tome::doctor::collect_doctor_view`] — the GUI-facing projection of
	 *  `DoctorReport` that exposes only the 6 surfaced finding categories (4
	 *  auto-fixable + 2 informational) plus pre-computed `auto_fixable_count` /
	 *  `manual_count` so the React section headers render without re-walking the
	 *  list. Non-GUI issues (orphan dirs, missing SKILL.md, config issues,
	 *  foreign symlinks) intentionally do NOT cross the IPC boundary in Phase 26.
	 */
	getDoctorReport: () => typedError<DoctorView_Serialize, TomeError>(__TAURI_INVOKE("get_doctor_report")),
	/**
	 *  Dispatch a per-item doctor repair for the GUI's `PreviewPopover` Apply
	 *  button (Phase 26 plan 26-05 / VIEW-05 / D-09).
	 * 
	 *  Wraps [`tome::doctor::repair_one`] — re-runs `check()` to locate the live
	 *  issue, then matches the [`tome::doctor::RepairKind`] exhaustively against
	 *  per-item helpers. NF-04 preview-then-confirm: this command is only reached
	 *  after the user clicks Apply inside the `PreviewPopover` (no keyboard
	 *  shortcut bypasses it; T-26-05-01 mitigation).
	 * 
	 *  Returns a structured `TomeError` for the two GUI-visible failure modes:
	 *  stale FindingId ("no longer present" — T-26-05-02), or non-auto-fixable
	 *  kind ("not auto-fixable" — defensive, the GUI never sends one of these).
	 *  The watcher (plan 26-06) fires `LibraryChanged` / `ManifestChanged` /
	 *  `MachinePrefsChanged` for the resulting writes; the React Health view
	 *  refetches on those.
	 */
	doctorRepairOne: (findingId: FindingId) => typedError<null, TomeError>(__TAURI_INVOKE("doctor_repair_one", { findingId })),
};

/** Events */
export const events = {
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	lockfileChanged: makeEvent<LockfileChanged>("lockfile-changed"),
	machinePrefsChanged: makeEvent<MachinePrefsChanged>("machine-prefs-changed"),
	manifestChanged: makeEvent<ManifestChanged>("manifest-changed"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
};

/* Types */
/**  A validated SHA-256 content hash (64 hex characters). */
export type ContentHash = string;

/**  A count that may have failed with an error message. */
export type CountOrError = CountOrError_Serialize | CountOrError_Deserialize;

/**  A count that may have failed with an error message. */
export type CountOrError_Deserialize = {
	count: number | null,
	error: string | null,
};

/**  A count that may have failed with an error message. */
export type CountOrError_Serialize = {
	count: number | null,
	error?: string | null,
};

/**
 *  A validated directory name.
 * 
 *  Rejects empty names and path separators, matching the `SkillName` validation pattern.
 */
export type DirectoryName = string;

/**
 *  The role a directory plays in the sync pipeline.
 * 
 *  The `clap::ValueEnum` derive lets `tome add --role <ROLE>` accept these
 *  variants in their kebab-case form (matching the `tome.toml` wire format).
 */
export type DirectoryRole = 
/**  Read-only, owned by package manager (e.g. Claude plugins cache) */
"managed" | 
/**  Skills discovered here AND distributed here (bidirectional) */
"synced" | 
/**  Skills discovered here, not distributed here */
"source" | 
/**  Skills distributed here, not discovered here */
"target";

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus = DirectoryStatus_Serialize | DirectoryStatus_Deserialize;

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus_Deserialize = {
	name: string,
	directory_type: string,
	role: DirectoryRole,
	/**
	 *  Human-readable description of the role (e.g. `"Synced (skills
	 *  discovered here AND distributed here)"`). Display-only — GUI
	 *  consumers should branch on [`role`](Self::role) instead.
	 */
	role_description: string,
	path: string,
	/**
	 *  Number of skills discovered (for discovery dirs) or symlinks present (for target dirs),
	 *  or an error message if counting failed.
	 */
	skill_count: CountOrError_Deserialize,
	/**  Warnings emitted during discovery. */
	warnings: string[],
	/**
	 *  True iff `directories.<name>.path` was rewritten by a `machine.toml`
	 *  `[directory_overrides.<name>]` entry during config load (PORT-05).
	 *  JSON consumers can use this to render the same context that text-mode
	 *  `tome status` shows via the `(override)` annotation.
	 */
	override_applied: boolean,
};

/**
 *  Status of a single configured directory.
 * 
 *  **JSON shape change (v0.11+):** `role` is now the typed
 *  `DirectoryRole` enum (serializes as `"managed"` / `"synced"` /
 *  `"source"` / `"target"`) so GUI consumers can branch on the role
 *  without parsing prose. The human-readable description previously
 *  in `role` (e.g. `"Synced (skills discovered here AND distributed
 *  here)"`) moved to `role_description`. Per the project's
 *  `Backward compat: None` policy, JSON consumers that read `role` as
 *  a description string need to switch to `role_description` or to the
 *  enum-aware reader.
 */
export type DirectoryStatus_Serialize = {
	name: string,
	directory_type: string,
	role: DirectoryRole,
	/**
	 *  Human-readable description of the role (e.g. `"Synced (skills
	 *  discovered here AND distributed here)"`). Display-only — GUI
	 *  consumers should branch on [`role`](Self::role) instead.
	 */
	role_description: string,
	path: string,
	/**
	 *  Number of skills discovered (for discovery dirs) or symlinks present (for target dirs),
	 *  or an error message if counting failed.
	 */
	skill_count: CountOrError_Serialize,
	/**  Warnings emitted during discovery. */
	warnings: string[],
	/**
	 *  True iff `directories.<name>.path` was rewritten by a `machine.toml`
	 *  `[directory_overrides.<name>]` entry during config load (PORT-05).
	 *  JSON consumers can use this to render the same context that text-mode
	 *  `tome status` shows via the `(override)` annotation.
	 */
	override_applied: boolean,
};

/**
 *  A discovered skill with its metadata.
 * 
 *  Crosses the Tauri IPC boundary as the row type backing the GUI's Skills
 *  view (`list_skills` Tauri command, plan 26-02 Task 2). The `frontmatter`
 *  field is skipped on serialization to keep payload size proportional to the
 *  VIEW-02 row contract — the detail pane fetches frontmatter via its own
 *  command in plan 26-03. `path` is serialized as a string for cross-boundary
 *  compatibility (Rust `PathBuf` → TS `string`).
 */
export type DiscoveredSkill = {
	/**  Skill name (directory name) */
	name: SkillName,
	/**  Path to the skill directory (contains SKILL.md) */
	path: string,
	/**  Which configured directory this skill came from (matches a key in `Config::directories`). */
	source_name: DirectoryName,
	/**  How this skill was sourced (managed vs local), with optional provenance metadata. */
	origin: SkillOrigin,
};

/**
 *  Wire-shape for a single doctor finding crossing the Tauri IPC boundary
 *  (Phase 26 plan 26-05).
 * 
 *  Distinct from the internal `DiagnosticIssue` to keep the GUI contract
 *  stable as `DiagnosticIssue` evolves. The React Health view renders
 *  `title` + `description` per row; `dry_run_description` populates the
 *  `PreviewPopover` body for auto-fixable findings.
 */
export type DoctorFinding = DoctorFinding_Serialize | DoctorFinding_Deserialize;

/**
 *  Wire-shape for a single doctor finding crossing the Tauri IPC boundary
 *  (Phase 26 plan 26-05).
 * 
 *  Distinct from the internal `DiagnosticIssue` to keep the GUI contract
 *  stable as `DiagnosticIssue` evolves. The React Health view renders
 *  `title` + `description` per row; `dry_run_description` populates the
 *  `PreviewPopover` body for auto-fixable findings.
 */
export type DoctorFinding_Deserialize = {
	/**
	 *  Stable content-aware identifier — round-trips back through
	 *  `doctor_repair_one(finding_id)` to dispatch the per-item repair.
	 */
	id: FindingId,
	severity: IssueSeverity,
	category: IssueCategory,
	/**
	 *  Short human label (e.g. "Broken library symlink", "Unparsable SKILL.md
	 *  frontmatter — {skill}"). Renders as the `FindingRow`'s primary line.
	 */
	title: string,
	/**
	 *  Verbatim diagnostic message from the underlying `DiagnosticIssue`.
	 *  Renders as the `FindingRow`'s secondary description.
	 */
	description: string,
	/**
	 *  Auto-repair classifier. `Some(kind)` ↔ the row exposes a Fix button
	 *  that opens the `PreviewPopover`; `None` → manual remediation hint
	 *  (D-12, never a dead control).
	 */
	repair_kind: RepairKind | null,
	/**
	 *  One-sentence dry-run description rendered as the `PreviewPopover` body
	 *  (NF-04 preview-then-confirm). Populated from `repair_kind_action_label`
	 *  when `repair_kind.is_some()`; `None` otherwise.
	 */
	dry_run_description: string | null,
};

/**
 *  Wire-shape for a single doctor finding crossing the Tauri IPC boundary
 *  (Phase 26 plan 26-05).
 * 
 *  Distinct from the internal `DiagnosticIssue` to keep the GUI contract
 *  stable as `DiagnosticIssue` evolves. The React Health view renders
 *  `title` + `description` per row; `dry_run_description` populates the
 *  `PreviewPopover` body for auto-fixable findings.
 */
export type DoctorFinding_Serialize = {
	/**
	 *  Stable content-aware identifier — round-trips back through
	 *  `doctor_repair_one(finding_id)` to dispatch the per-item repair.
	 */
	id: FindingId,
	severity: IssueSeverity,
	category: IssueCategory,
	/**
	 *  Short human label (e.g. "Broken library symlink", "Unparsable SKILL.md
	 *  frontmatter — {skill}"). Renders as the `FindingRow`'s primary line.
	 */
	title: string,
	/**
	 *  Verbatim diagnostic message from the underlying `DiagnosticIssue`.
	 *  Renders as the `FindingRow`'s secondary description.
	 */
	description: string,
	/**
	 *  Auto-repair classifier. `Some(kind)` ↔ the row exposes a Fix button
	 *  that opens the `PreviewPopover`; `None` → manual remediation hint
	 *  (D-12, never a dead control).
	 */
	repair_kind?: RepairKind | null,
	/**
	 *  One-sentence dry-run description rendered as the `PreviewPopover` body
	 *  (NF-04 preview-then-confirm). Populated from `repair_kind_action_label`
	 *  when `repair_kind.is_some()`; `None` otherwise.
	 */
	dry_run_description?: string | null,
};

/**
 *  Wire-shape for the GUI Health view's full payload (Phase 26 plan 26-05).
 * 
 *  Stable on the IPC boundary — the React side renders
 *  `auto_fixable_count` / `manual_count` in the section headers and iterates
 *  `findings` once to partition into the AUTO-FIXABLE / NEEDS ATTENTION
 *  sections.
 */
export type DoctorView = DoctorView_Serialize | DoctorView_Deserialize;

/**
 *  Wire-shape for the GUI Health view's full payload (Phase 26 plan 26-05).
 * 
 *  Stable on the IPC boundary — the React side renders
 *  `auto_fixable_count` / `manual_count` in the section headers and iterates
 *  `findings` once to partition into the AUTO-FIXABLE / NEEDS ATTENTION
 *  sections.
 */
export type DoctorView_Deserialize = {
	findings: DoctorFinding_Deserialize[],
	auto_fixable_count: number,
	manual_count: number,
};

/**
 *  Wire-shape for the GUI Health view's full payload (Phase 26 plan 26-05).
 * 
 *  Stable on the IPC boundary — the React side renders
 *  `auto_fixable_count` / `manual_count` in the section headers and iterates
 *  `findings` once to partition into the AUTO-FIXABLE / NEEDS ATTENTION
 *  sections.
 */
export type DoctorView_Serialize = {
	findings: DoctorFinding_Serialize[],
	auto_fixable_count: number,
	manual_count: number,
};

/**
 *  Coarse, stable error categories surfaced to the front-end (D-15).
 * 
 *  Grows additively. The GUI branches on this discriminant; new variants are a
 *  non-breaking superset. Mirrors `tome::DomainErrorKind` plus an `Internal`
 *  fallback (the domain enum deliberately omits `Internal` — see its docs).
 */
export type ErrorCode = 
/**  Input/config validation failure. */
"Validation" | 
/**  A required path/config/resource was not found. */
"NotFound" | 
/**  A filesystem operation was denied by the OS. */
"Permission" | 
/**  A content-hash or path-overlap collision. */
"Conflict" | 
/**  A `git` clone/update operation failed. */
"Git" | 
/**  A generic I/O failure. */
"Io" | 
/**  Anything not classified by a domain sentinel (the fallback, D-14). */
"Internal";

/**
 *  Stable, content-aware identifier for a single doctor finding (Phase 26
 *  plan 26-05, OQ-2 resolution).
 * 
 *  Used to dispatch per-item repairs through `repair_one`: the GUI sends the
 *  `FindingId` it harvested from the last `collect_doctor_view` snapshot, and
 *  `repair_one` re-runs `check()` to locate the matching live issue. The
 *  content-aware enum (variants carry the identifying data inline) avoids the
 *  hash-collision class hash-style IDs would invite (T-26-05-03).
 * 
 *  Variants align 1:1 with the 4 [`RepairKind`] auto-fix arms plus 2
 *  informational categories ([`Self::UnparsableFrontmatter`],
 *  [`Self::DivergingTarget`]) the UI surfaces with manual remediation hints.
 * 
 *  JSON wire-shape: `{ "kind": "library_stale_manifest", "skill": "name" }` etc.
 * 
 *  Per POLISH-04: `ALL` array + compile-time exhaustiveness sentinel pin every
 *  variant. Adding a variant without updating `ALL` is a `cargo check` failure.
 */
export type FindingId = 
/**
 *  Manifest entry whose library directory is missing on disk (also covers
 *  broken managed symlinks — same repair handler).
 */
{ kind: "library_stale_manifest"; skill: SkillName } | 
/**  Broken legacy symlink in the library directory (not in the manifest). */
{ kind: "library_broken_symlink"; path: string } | 
/**
 *  Stale symlink in a distribution directory (points into the library at
 *  a now-missing skill).
 */
{ kind: "target_stale_symlink"; directory: DirectoryName; path: string } | 
/**
 *  Real directory in a distribution directory whose content matches a
 *  library skill byte-for-byte (Phase 24 — auto-fixable by replacing with
 *  a symlink).
 */
{ kind: "target_real_dir_to_symlink"; directory: DirectoryName; path: string } | 
/**
 *  Library skill whose `SKILL.md` YAML frontmatter does not parse
 *  (informational; user must edit the file). Phase 23.
 */
{ kind: "unparsable_frontmatter"; skill: SkillName } | 
/**
 *  Real directory in a distribution directory whose content diverges from
 *  the matching library skill (informational; user must reconcile
 *  manually).
 */
{ kind: "diverging_target"; directory: DirectoryName; path: string };

/**
 *  Category of a [`DiagnosticIssue`]. Derived at construction from the
 *  [`DoctorReport`] field the issue lives in, with `ForeignSymlink`
 *  promoted regardless of source field per D-CAT-1.
 * 
 *  JSON serialisation is snake_case (`"library"`, `"directory"`,
 *  `"config"`, `"foreign_symlink"`), matching the project convention.
 * 
 *  Per POLISH-04: `ALL` array + compile-time exhaustiveness sentinel
 *  keep every variant pinned. Adding a variant without updating `ALL`
 *  is a `cargo check` failure.
 */
export type IssueCategory = "library" | "directory" | "config" | "foreign_symlink";

/**  Severity of a diagnostic issue. */
export type IssueSeverity = 
/**  Critical problem (e.g., missing directory, broken symlink). */
"Error" | 
/**  Non-critical problem (e.g., orphan directory, missing source path). */
"Warning";

/**
 *  Library directory contents changed (skill add/remove/edit).
 * 
 *  React hooks that depend on library content (status, skills list, detail,
 *  doctor) refetch on this event. Recursive mode for `<tome_home>/skills/`.
 */
export type LibraryChanged = null;

/**
 *  The structured result of `tome list`: every discovered skill (sorted by
 *  name) plus any non-fatal discovery warnings.
 * 
 *  Field shapes are deliberately the same `DiscoveredSkill` / `String` types
 *  the rest of the crate already uses — no list-specific wrapper types — so the
 *  GUI consumes the same vocabulary the CLI does (the library-canonical types
 *  are the contract, STATE.md).
 */
export type ListReport = {
	/**  Discovered skills, sorted alphabetically by skill name. */
	skills: DiscoveredSkill[],
	/**
	 *  Non-fatal warnings emitted during discovery (naming-convention hints,
	 *  deduplication notices). The CLI prints these to stderr unless `--quiet`;
	 *  the GUI can surface them in a diagnostics view.
	 */
	warnings: string[],
};

/**
 *  The lockfile (`tome.lock`) was rewritten.
 * 
 *  React hooks that surface lockfile state (status, doctor) refetch on this
 *  event. Skills/detail views do NOT subscribe because lockfile changes don't
 *  affect the discovered skill list shape (NF-05 contract).
 */
export type LockfileChanged = null;

/**
 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
 * 
 *  Classification reuses the same content-hash comparison `reconcile.rs`
 *  performs against the marketplace: every lockfile entry must have a
 *  matching manifest entry whose `content_hash` equals the lockfile-recorded
 *  value. Any divergence (missing manifest entry OR hash mismatch) increments
 *  `drift_count`.
 * 
 *  Variant tag style matches the GUI's discriminated-union pattern (D-GUI-08):
 *  the serialized shape is `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`
 *  so the React side can pattern-match without parsing strings.
 */
export type LockfileState = 
/**  Every lockfile entry's `content_hash` matches the manifest. */
{ kind: "in_sync" } | 
/**
 *  At least one lockfile entry has no matching manifest hash. `drift_count`
 *  counts the divergent entries (mismatch + missing manifest combined).
 */
{ kind: "out_of_sync"; drift_count: number } | 
/**  `tome.lock` does not exist on disk (fresh `tome_home`, never synced). */
{ kind: "missing" };

/**
 *  Per-machine preferences (`machine.toml`) were rewritten.
 * 
 *  Fires for own-process writes too (Phase-26 mutation D-06 — verified by the
 *  integration test in `tests/watcher_smoke.rs`). React hooks whose render
 *  branches on disabled/enabled state (status, skills, detail) refetch.
 */
export type MachinePrefsChanged = null;

/**
 *  Per-machine prefs summary shown in the Status view (VIEW-01).
 * 
 *  Surfaces the integer counts the Status view's `MACHINE` row renders
 *  ("N skills disabled"). Counts only — the full skill / directory lists
 *  stay in `machine.toml`.
 */
export type MachinePrefsSummary = {
	/**
	 *  `MachinePrefs.disabled.len()` — count of skills globally disabled
	 *  on this machine.
	 */
	disabled_count: number,
	/**
	 *  `MachinePrefs.disabled_directories.len()` — count of directories
	 *  disabled on this machine.
	 */
	disabled_directory_count: number,
};

/**
 *  The on-disk manifest (`.tome-manifest.json`) was rewritten.
 * 
 *  React hooks that derive from manifest state (skill list, status, doctor)
 *  refetch on this event.
 */
export type ManifestChanged = null;

/**
 *  Categorises the auto-repair available for a [`DiagnosticIssue`]
 *  (D-REPAIR-1).
 * 
 *  `Some(kind)` on [`DiagnosticIssue::repair_kind`] ↔ the issue is
 *  auto-fixable and the global repair dispatcher in [`diagnose`] has a
 *  handler arm for `kind`. `None` means the issue requires user
 *  interaction (e.g. orphan directories, which use a per-item Select
 *  prompt) or is informational only.
 * 
 *  JSON serialisation is snake_case
 *  (`"remove_stale_manifest_entry"`, `"remove_broken_library_symlink"`,
 *  `"remove_stale_target_symlink"`).
 * 
 *  Per POLISH-04: `ALL` array + compile-time exhaustiveness sentinel
 *  pin every variant. The repair dispatcher matches exhaustively on
 *  `Option<RepairKind>` — adding a variant without a handler arm fails
 *  to compile.
 */
export type RepairKind = 
/**
 *  Remove a manifest entry whose library directory is missing on
 *  disk OR whose managed symlink is broken. Emit sites in
 *  `check_library` (both cases share the action:
 *  `Manifest::remove(name)` plus `remove_file` if the entry is a
 *  symlink).
 */
"remove_stale_manifest_entry" | 
/**
 *  Remove a broken legacy symlink in the library directory (not
 *  referenced by the manifest). Emit site: `check_library`
 *  "broken legacy symlink: X -> Y". Action: `remove_file(path)`.
 */
"remove_broken_library_symlink" | 
/**
 *  Remove a stale symlink from a distribution directory. Emit
 *  site: `check_distribution_dir` "stale symlink X". Action:
 *  `cleanup::cleanup_target` removes broken symlinks pointing into
 *  the library.
 */
"remove_stale_target_symlink" | 
/**
 *  Phase 24 (v0.16+): a real directory in a distribution dir whose
 *  content matches a library skill byte-for-byte (typically a
 *  pre-tome manual copy or a user dropping skills in by hand).
 *  Repair removes the real directory and replaces it with a
 *  symlink into the library — converging on the v0.10 distribution
 *  model. Emit site: `check_distribution_dir` "matches library
 *  content (should be a symlink)". Diverging content stays a
 *  no-repair Warning (the user must reconcile).
 */
"consolidate_target_real_dir_to_symlink";

/**
 *  GUI-facing aggregate of everything a single skill exposes (Phase 26 plan
 *  26-03 / VIEW-03 / D-05).
 * 
 *  Owned by the right-pane DetailHeader + MarkdownBody in the React UI. The
 *  shape is intentionally projection-flat: no nested manifest type leaks
 *  across the IPC edge.
 */
export type SkillDetail = {
	name: SkillName,
	/**
	 *  Resolved source-of-truth path (manifest source for Owned skills,
	 *  library-canonical copy for Unowned). Computed by
	 *  [`crate::actions::resolve_source_path`].
	 */
	source_path: string,
	/**  SHA-256 of the source directory at the last sync. */
	content_hash: ContentHash,
	/**
	 *  ISO-8601 timestamp of the last sync; the manifest tracks this per
	 *  entry. Always populated for entries that exist in the manifest.
	 */
	last_sync: string | null,
	/**
	 *  Whether the skill's source directory is managed by a package
	 *  manager (true) or a local directory (false).
	 */
	managed: boolean,
	/**
	 *  Whether the skill is currently in the **global** `disabled` set in
	 *  `machine.toml` on this machine.
	 */
	disabled: boolean,
	/**  Parsed frontmatter (specta-friendly projection). */
	frontmatter: SkillFrontmatterView,
	/**
	 *  Post-frontmatter markdown body. Capped at [`SKILL_BODY_MAX_BYTES`]
	 *  (1 MiB) with an inline truncation marker beyond that.
	 */
	body: string,
};

/**
 *  Specta-friendly projection of [`SkillFrontmatter`] crossing the GUI IPC
 *  boundary.
 * 
 *  The CLI-side [`SkillFrontmatter`] type carries unstructured `metadata` and
 *  `extra` maps keyed by `String → serde_yaml::Value`. specta's `serde_yaml`
 *  support is not enabled in this crate (would add a heavier transitive dep
 *  for ad-hoc YAML), and `serde_json::Value` is recursive and can't be
 *  inlined by specta's TypeScript exporter. So the GUI ships **JSON-encoded
 *  string blobs** for the unstructured fields — the JS side `JSON.parse`s
 *  them on demand. The known-typed fields (name / description / license /
 *  ...) keep their native Rust types.
 * 
 *  Phase 26 alpha (plan 26-03) doesn't actually render `metadata` / `extra`
 *  in the DetailHeader — those fields ride along for plan 26-04 (markdown
 *  body) and beyond. The string-encoded shape lands a clean TS schema; the
 *  JS side parses values only when a downstream UI surface needs them.
 */
export type SkillFrontmatterView = {
	name: string | null,
	description: string | null,
	license: string | null,
	compatibility: string | null,
	allowed_tools: string | null,
	/**  Claude Code extension — `user-invocable: false` flag. */
	user_invocable: boolean | null,
	argument_hint: string | null,
	context: string | null,
	agent: string | null,
	/**
	 *  Structured `metadata` map (YAML→JSON, then each value serialized as a
	 *  JSON string blob — avoids specta's "recursive inline type" panic on
	 *  `serde_json::Value`). `None` when the frontmatter has no `metadata`
	 *  key. The JS side `JSON.parse`s individual entries on demand.
	 */
	metadata: { [key in string]: string } | null,
	/**
	 *  Unknown / non-standard top-level frontmatter fields. Same
	 *  YAML→JSON→string encoding as `metadata`. Empty map when the
	 *  frontmatter is fully canonical.
	 */
	extra: { [key in string]: string },
};

/**
 *  A validated skill name.
 * 
 *  Lenient validation: rejects empty names and path separators.
 *  Warns on names that don't match the strict `[a-z0-9-]+` pattern
 *  (which may become a hard requirement in a future version).
 */
export type SkillName = string;

/**
 *  How a skill was sourced — determines consolidation strategy.
 * 
 *  The IPC boundary serializes this as a discriminated union shaped
 *  `{ "kind": "managed" | "local", ... }` so the GUI can pattern-match
 *  the kind without parsing strings — same shape as `LockfileState`
 *  from plan 26-01.
 */
export type SkillOrigin = 
/**
 *  Managed by a package manager (v0.10+: stored as a real-directory
 *  copy in the library, NOT a symlink). The `managed: true` manifest
 *  flag marks the update channel — upstream sync feeds the copy via
 *  `MarketplaceAdapter`. Pre-v0.10 stored managed skills as symlinks
 *  into the source dir; that shape is now refused at the sync gate
 *  (see `library::consolidate_managed` and `migration_v010`).
 */
{ kind: "managed"; provenance: SkillProvenance | null } | 
/**
 *  Local skill; library entry is a real-directory copy of the source.
 *  The library copy is editable in-place; `tome sync` detects drift
 *  via content_hash comparison.
 */
{ kind: "local" };

/**  Provenance metadata from package manager sources. */
export type SkillProvenance = {
	/**  Registry identifier (e.g. "my-plugin@npm") */
	registry_id: string,
	/**  Version string (e.g. "1.2.0"). `None` when not available. */
	version: string | null,
	/**  Git commit SHA for exact version pinning. `None` when not available. */
	git_commit_sha: string | null,
};

/**
 *  One row of the Unowned section in `tome status` and `tome doctor`.
 *  Per D-D3 in the Phase 14 CONTEXT.md.
 */
export type SkillSummary = {
	/**  Skill name as displayed. */
	name: string,
	/**
	 *  Last directory that owned this skill, captured at transition time
	 *  (D-C1). `None` for entries that became Unowned before Phase 14
	 *  landed — consumers fall back to `source_path_display` (D-C2).
	 */
	previous_source: string | null,
	/**
	 *  `paths::collapse_home`-rendered `source_path` from the manifest.
	 *  Always populated; serves as the D-C2 fallback when
	 *  `previous_source` is `None`, and as supplementary info otherwise.
	 */
	source_path_display: string,
	/**
	 *  ISO 8601 timestamp from the manifest (preserved across Owned→Unowned
	 *  transition per Phase 11 manifest semantics).
	 */
	synced_at: string,
	/**
	 *  Mirrors `SkillEntry::managed`. Display-only; consumers may want
	 *  to surface "originally a managed plugin" for context.
	 */
	managed: boolean,
};

/**  Complete status report for the tome system. */
export type StatusReport = StatusReport_Serialize | StatusReport_Deserialize;

/**  Complete status report for the tome system. */
export type StatusReport_Deserialize = {
	configured: boolean,
	library_dir: string,
	/**  Number of skills consolidated in the library, or an error message. */
	library_count: CountOrError_Deserialize,
	/**
	 *  RFC-3339 timestamp of last successful sync; `null` if never synced
	 *  or pre-v0.11 manifest. Per D-LSYNC-2 (OBS-07): "never" in text;
	 *  `null` in JSON. No `skip_serializing_if` — emit `"last_sync": null`
	 *  for stable-shape JSON consumers (matches `unowned: []` pattern).
	 */
	last_sync: string | null,
	directories: DirectoryStatus_Deserialize[],
	/**
	 *  Skills in the library whose source was removed from `tome.toml`
	 *  (Unowned per LIB-04). Surfaces in text rendering between the
	 *  Directories table and the Health line (D-D2). Always present in
	 *  JSON output for stable shape; empty array when no Unowned skills.
	 */
	unowned: SkillSummary[],
	/**
	 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
	 *  Surfaces in the Status view's `LOCKFILE` row paired with `StatusDot`.
	 *  JSON shape: `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`.
	 */
	lockfile: LockfileState,
	/**
	 *  Per-machine prefs summary (VIEW-01). Surfaces in the Status view's
	 *  `MACHINE` row ("N skills disabled").
	 */
	machine_prefs_summary: MachinePrefsSummary,
	/**  Number of health issues, or an error message. */
	health: CountOrError_Deserialize,
};

/**  Complete status report for the tome system. */
export type StatusReport_Serialize = {
	configured: boolean,
	library_dir: string,
	/**  Number of skills consolidated in the library, or an error message. */
	library_count: CountOrError_Serialize,
	/**
	 *  RFC-3339 timestamp of last successful sync; `null` if never synced
	 *  or pre-v0.11 manifest. Per D-LSYNC-2 (OBS-07): "never" in text;
	 *  `null` in JSON. No `skip_serializing_if` — emit `"last_sync": null`
	 *  for stable-shape JSON consumers (matches `unowned: []` pattern).
	 */
	last_sync: string | null,
	directories: DirectoryStatus_Serialize[],
	/**
	 *  Skills in the library whose source was removed from `tome.toml`
	 *  (Unowned per LIB-04). Surfaces in text rendering between the
	 *  Directories table and the Health line (D-D2). Always present in
	 *  JSON output for stable shape; empty array when no Unowned skills.
	 */
	unowned: SkillSummary[],
	/**
	 *  State of `tome.lock` relative to the on-disk manifest (VIEW-01).
	 *  Surfaces in the Status view's `LOCKFILE` row paired with `StatusDot`.
	 *  JSON shape: `{ "kind": "in_sync" | "out_of_sync" | "missing", ... }`.
	 */
	lockfile: LockfileState,
	/**
	 *  Per-machine prefs summary (VIEW-01). Surfaces in the Status view's
	 *  `MACHINE` row ("N skills disabled").
	 */
	machine_prefs_summary: MachinePrefsSummary,
	/**  Number of health issues, or an error message. */
	health: CountOrError_Serialize,
};

/**
 *  Front-end progress event streamed to the webview.
 * 
 *  Carries the **typed** [`SyncStage`] enum directly (not a stringified label)
 *  so the front-end can pattern-match the stage — WARNING 4's typed option.
 *  `SyncStage` already derives gated `specta::Type` and is `Copy` (25-02), so
 *  it crosses the boundary as a TS string-union discriminant.
 */
export type SyncProgress = {
	/**  Which pipeline stage this event refers to. */
	stage: SyncStage,
	/**  Units processed so far in this stage (0 when not applicable). */
	current: number,
	/**  Total units in this stage (0 when unknown / not applicable). */
	total: number,
};

/**
 *  The pipeline stage a [`ProgressEvent`] refers to.
 * 
 *  Mirrors the six stages of the `sync` pipeline (see the crate-level docs):
 *  Reconcile → Discover → Consolidate → Distribute → Cleanup → Save. Kept as a
 *  typed enum (not a `&str`) so the GUI exhaustively matches stages (D-10).
 */
export type SyncStage = 
/**  Lockfile-authoritative drift detection for managed skills. */
"Reconcile" | 
/**  Scan configured directories for `*\/SKILL.md` directories. */
"Discover" | 
/**  Copy discovered skills into the library (library-canonical model). */
"Consolidate" | 
/**  Push library skills to target tools via symlinks. */
"Distribute" | 
/**  Three-bucket stale-skill report + orphan transitions. */
"Cleanup" | 
/**  Persist manifest, lockfile, and `.gitignore`. */
"Save";

/**
 *  The structured error payload that crosses the Tauri IPC boundary (D-16).
 * 
 *  - `code`: the stable [`ErrorCode`] the GUI pattern-matches on.
 *  - `message`: the top-level error string (`err.to_string()`).
 *  - `context`: the flattened anyhow cause chain, outermost first — the same
 *    information the CLI prints via `{e:#}`, available for a details view.
 */
export type TomeError = {
	/**  Stable, coarse classification. */
	code: ErrorCode,
	/**  Top-level human-readable message. */
	message: string,
	/**  Flattened anyhow `.context()` chain (outermost first). */
	context: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

