// Tauri API mock (axe-core/playwright a11y gate, plan 26-07 Task 3;
// playwright perf bench, plan 26-08 Task 2).
//
// Replaces `@tauri-apps/api/core` when `A11Y_TEST=1` OR `PERF_TEST=1`
// (Vite alias in `vite.config.ts`). Returns deterministic fixture data
// so the React render tree exercises every interactive surface either
// gate scans:
//
// - Status view: configured + library count + lockfile + machine prefs.
// - Skills view: 3 representative skills (1 managed, 2 local, 1 disabled).
// - Skill detail: realistic SKILL.md frontmatter projection.
// - Doctor report: 1 auto-fixable finding + 1 manual finding so the
//   AUTO-FIXABLE / NEEDS ATTENTION headings + FindingRow + Fix button
//   (which gates the PreviewPopover) all render.
//
// This is NOT a Tauri-runtime fidelity test — the real IPC behaviour is
// verified by the watcher integration test in plan 26-06. This mock
// only guarantees that the React render tree is well-formed for axe to
// scan.

/* eslint-disable @typescript-eslint/no-explicit-any */

// Fixture data — keep small but representative.
const STATUS_REPORT = {
  configured: true,
  library_dir: "/Users/test/.tome/skills",
  library_count: { count: 3, error: null },
  last_sync: "2026-05-29T08:00:00Z",
  directories: [
    {
      name: "claude-plugins",
      directory_type: "claude-plugins",
      role: "managed",
      role_description: "Managed (skills discovered here, read-only)",
      path: "/Users/test/.claude/plugins",
      skill_count: { count: 1, error: null },
      warnings: [],
      override_applied: false,
    },
    {
      name: "personal",
      directory_type: "directory",
      role: "synced",
      role_description:
        "Synced (skills discovered here AND distributed here)",
      path: "/Users/test/skills",
      skill_count: { count: 2, error: null },
      warnings: [],
      override_applied: false,
    },
  ],
  unowned: [],
  lockfile: { kind: "in_sync" },
  machine_prefs_summary: {
    disabled_count: 1,
    disabled_directory_count: 0,
  },
  health: { count: 2, error: null },
};

/** A11y fixture — 3 representative skills (1 managed, 2 local). */
const A11Y_LIST_REPORT = {
  skills: [
    {
      name: "axiom-build",
      path: "/Users/test/.claude/plugins/axiom-build",
      source_name: "claude-plugins",
      origin: {
        kind: "managed",
        registry_id: "axiom",
        version: "1.2.3",
        git_commit_sha: null,
      },
    },
    {
      name: "rust-helper",
      path: "/Users/test/skills/rust-helper",
      source_name: "personal",
      origin: { kind: "local" },
    },
    {
      name: "deprecated-skill",
      path: "/Users/test/skills/deprecated-skill",
      source_name: "personal",
      origin: { kind: "local" },
    },
  ],
  warnings: [],
};

/** Perf fixture — 2000 synthetic skills generated by
 *  `tests/perf/synthetic_skills.rs`. The JSON file is copied to this
 *  directory by the bench harness (see `scripts/copy-perf-fixture.mjs`)
 *  so this static import resolves at Vite build time. The file is
 *  gitignored — a stub file ships in-tree so unrelated UI builds don't
 *  break on the missing import. */
import PERF_LIST_REPORT from "./perf-skills.json";

/** Selected at module load time — `import.meta.env.VITE_PERF_TEST` is
 *  pre-substituted by Vite's `define` plugin so this collapses to a
 *  constant at build time. When `PERF_TEST=1`, the listSkills mock
 *  returns the 2000-skill fixture; otherwise the 3-skill a11y fixture. */
const IS_PERF_TEST = import.meta.env.VITE_PERF_TEST === "1";
const LIST_REPORT = IS_PERF_TEST ? PERF_LIST_REPORT : A11Y_LIST_REPORT;

const SKILL_DETAIL_BY_NAME: Record<string, any> = {
  "axiom-build": {
    name: "axiom-build",
    source_path: "/Users/test/.claude/plugins/axiom-build",
    content_hash:
      "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234",
    last_sync: "2026-05-29T08:00:00Z",
    managed: true,
    disabled: false,
    frontmatter: {
      name: "axiom-build",
      description: "Build failures, Xcode, simulator, SPM",
      license: "MIT",
      compatibility: null,
      allowed_tools: null,
      metadata: "{}",
      extra: "{}",
    },
    body: "# Axiom Build\n\nHelp with iOS build issues.",
  },
};

const DOCTOR_REPORT = {
  findings: [
    {
      id: { kind: "library_broken_symlink", path: "/Users/test/.tome/skills/orphan" },
      severity: "warning",
      category: "library",
      title: "Broken library symlink",
      description:
        "The symlink at /Users/test/.tome/skills/orphan points at a directory that no longer exists.",
      repair_kind: "remove_broken_library_symlink",
      dry_run_description:
        "Remove the broken symlink at /Users/test/.tome/skills/orphan.",
    },
    {
      id: {
        kind: "skill_unparsable_frontmatter",
        skill: "deprecated-skill",
      },
      severity: "blocked",
      category: "skill",
      title: "Unparsable SKILL.md frontmatter — deprecated-skill",
      description:
        "The YAML frontmatter delimiters are missing in /Users/test/skills/deprecated-skill/SKILL.md.",
      repair_kind: null,
      dry_run_description: null,
    },
  ],
  auto_fixable_count: 1,
  manual_count: 1,
};

/** Mocked invoke — switches on command name and returns the
 *  command's wrapped `Ok` payload (matching the `typedError` wrap that
 *  bindings.ts generates). */
export async function invoke(cmd: string, _args?: any): Promise<any> {
  switch (cmd) {
    case "get_status":
      return STATUS_REPORT;
    case "list_skills":
      return LIST_REPORT;
    case "get_skill_detail": {
      const name: string = _args?.name ?? "";
      return SKILL_DETAIL_BY_NAME[name] ?? SKILL_DETAIL_BY_NAME["axiom-build"];
    }
    case "set_skill_disabled":
      return null;
    case "open_source_folder":
      return null;
    case "copy_path":
      return "/Users/test/.claude/plugins/axiom-build";
    case "get_doctor_report":
      return DOCTOR_REPORT;
    case "doctor_repair_one":
      return null;
    // Phase 27 plan 27-01b — long-running sync pipeline commands.
    // The axe-core gate only scans the initial render tree; it never
    // exercises an actual sync. start_sync returns immediately with a
    // success unit so the SyncView's terminal-state placeholder renders
    // if the gate happens to click [Run sync]. cancel_sync is idempotent
    // on the Rust side and returns unit too.
    case "start_sync":
      return null;
    case "cancel_sync":
      return null;
    // Phase 27 plan 27-02 — SYNC-02 triage panel projection. The a11y gate
    // doesn't visit the in-progress state today, but the mock returns an
    // empty diff so if it does, the panel collapses to nothing rather than
    // raising "unknown command".
    case "get_lockfile_diff":
      return { added: [], changed: [], removed: [] };
    default:
      throw new Error(`a11y mock: unknown command '${cmd}'`);
  }
}

// Re-export the symbols `@tauri-apps/api/core` exposes that we touch.
export const transformCallback = (_cb: any) => 0;
export const Channel = class {
  onmessage: (() => void) | null = null;
};
