// Tauri API mock (axe-core/playwright a11y gate, plan 26-07 Task 3;
// playwright perf bench, plan 26-08 Task 2).
//
// Replaces `@tauri-apps/api/core` when `A11Y_TEST=1` OR `PERF_TEST=1`
// (Vite alias in `vite.config.ts`). Returns deterministic fixture data
// so the React render tree exercises every interactive surface either
// gate scans:
//
// - Status view: configured + library count + lockfile + machine prefs.
// - Skills view: 3 representative skills (1 managed, 2 local, 1 disabled).
// - Skill detail: realistic SKILL.md frontmatter projection.
// - Doctor report: 1 auto-fixable finding + 1 manual finding so the
//   AUTO-FIXABLE / NEEDS ATTENTION headings + FindingRow + Fix button
//   (which gates the PreviewPopover) all render.
//
// This is NOT a Tauri-runtime fidelity test — the real IPC behaviour is
// verified by the watcher integration test in plan 26-06. This mock
// only guarantees that the React render tree is well-formed for axe to
// scan.

/* eslint-disable @typescript-eslint/no-explicit-any */

// Fixture data — keep small but representative.
const STATUS_REPORT = {
  configured: true,
  library_dir: "/Users/test/.tome/skills",
  library_count: { count: 3, error: null },
  last_sync: "2026-05-29T08:00:00Z",
  directories: [
    {
      name: "claude-plugins",
      directory_type: "claude-plugins",
      role: "managed",
      role_description: "Managed (skills discovered here, read-only)",
      path: "/Users/test/.claude/plugins",
      skill_count: { count: 1, error: null },
      warnings: [],
      override_applied: false,
    },
    {
      name: "personal",
      directory_type: "directory",
      role: "synced",
      role_description:
        "Synced (skills discovered here AND distributed here)",
      path: "/Users/test/skills",
      skill_count: { count: 2, error: null },
      warnings: [],
      override_applied: false,
    },
  ],
  unowned: [],
  lockfile: { kind: "in_sync" },
  machine_prefs_summary: {
    disabled_count: 1,
    disabled_directory_count: 0,
  },
  health: { count: 2, error: null },
};

/** A11y fixture — 3 representative skills (1 managed, 2 local).
 *
 *  Phase 27 plan 27-02b adds `synced_at` (D-16) to each row so the
 *  new "skills view group-by Source passes axe WCAG-AA" subtest
 *  exercises the same field the Sort=Recent comparator keys on.
 *  Mixed null + populated values mirror the real-world shape (a skill
 *  freshly discovered but not yet synced has `synced_at = null`). */
const A11Y_LIST_REPORT = {
  skills: [
    {
      name: "axiom-build",
      path: "/Users/test/.claude/plugins/axiom-build",
      source_name: "claude-plugins",
      origin: {
        kind: "managed",
        provenance: {
          registry_id: "axiom",
          version: "1.2.3",
          git_commit_sha: null,
        },
      },
      synced_at: "2026-05-29T08:00:00Z",
    },
    {
      name: "rust-helper",
      path: "/Users/test/skills/rust-helper",
      source_name: "personal",
      origin: { kind: "local" },
      synced_at: "2026-05-28T08:00:00Z",
    },
    {
      name: "deprecated-skill",
      path: "/Users/test/skills/deprecated-skill",
      source_name: "personal",
      origin: { kind: "local" },
      synced_at: null,
    },
  ],
  warnings: [],
};

/** Perf fixture — 2000 synthetic skills generated by
 *  `tests/perf/synthetic_skills.rs`. The JSON file is copied to this
 *  directory by the bench harness (see `scripts/copy-perf-fixture.mjs`)
 *  so this static import resolves at Vite build time. The file is
 *  gitignored — a stub file ships in-tree so unrelated UI builds don't
 *  break on the missing import. */
import PERF_LIST_REPORT from "./perf-skills.json";

/** Selected at module load time — `import.meta.env.VITE_PERF_TEST` is
 *  pre-substituted by Vite's `define` plugin so this collapses to a
 *  constant at build time. When `PERF_TEST=1`, the listSkills mock
 *  returns the 2000-skill fixture; otherwise the 3-skill a11y fixture. */
const IS_PERF_TEST = import.meta.env.VITE_PERF_TEST === "1";
const LIST_REPORT = IS_PERF_TEST ? PERF_LIST_REPORT : A11Y_LIST_REPORT;

const SKILL_DETAIL_BY_NAME: Record<string, any> = {
  "axiom-build": {
    name: "axiom-build",
    source_path: "/Users/test/.claude/plugins/axiom-build",
    content_hash:
      "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234",
    last_sync: "2026-05-29T08:00:00Z",
    managed: true,
    disabled: false,
    frontmatter: {
      name: "axiom-build",
      description: "Build failures, Xcode, simulator, SPM",
      license: "MIT",
      compatibility: null,
      allowed_tools: null,
      metadata: "{}",
      extra: "{}",
    },
    body: "# Axiom Build\n\nHelp with iOS build issues.",
  },
};

/** Triage fixture — exercises GridList + nested SectionHeader + the
 *  TriageRow chip-toggle + the RadioGroup canonical picker. Two added
 *  entries (one managed-git, one local) + one changed + one removed
 *  covers every branch the triage UI renders. */
const TRIAGE_DIFF = {
  added: [
    {
      name: "axiom-build",
      change_kind: "added" as const,
      source_name: "plugins",
      previous_source: null,
      origin: {
        kind: "managed" as const,
        provenance: {
          registry_id: "axiom@npm",
          version: "1.2.0",
          git_commit_sha: "abc1234",
        },
      },
      content_hash_old: null,
      content_hash_new: "b".repeat(64),
      registry_id: "axiom@npm",
      version_old: null,
      version_new: "1.2.0",
      git_commit_sha_old: null,
      git_commit_sha_new: "abc1234",
      synced_at: null,
    },
    {
      name: "axiom-swiftui",
      change_kind: "added" as const,
      source_name: "personal",
      previous_source: null,
      origin: { kind: "local" as const },
      content_hash_old: null,
      content_hash_new: "c".repeat(64),
      registry_id: null,
      version_old: null,
      version_new: null,
      git_commit_sha_old: null,
      git_commit_sha_new: null,
      synced_at: null,
    },
  ],
  changed: [
    {
      name: "rust-helper",
      change_kind: "changed" as const,
      source_name: "personal",
      previous_source: null,
      origin: { kind: "local" as const },
      content_hash_old: "a".repeat(64),
      content_hash_new: "d".repeat(64),
      registry_id: null,
      version_old: null,
      version_new: null,
      git_commit_sha_old: null,
      git_commit_sha_new: null,
      synced_at: "2026-05-29T08:00:00Z",
    },
  ],
  removed: [
    {
      name: "deprecated-skill",
      change_kind: "removed" as const,
      source_name: "personal",
      previous_source: null,
      origin: { kind: "local" as const },
      content_hash_old: "e".repeat(64),
      content_hash_new: null,
      registry_id: null,
      version_old: null,
      version_new: null,
      git_commit_sha_old: null,
      git_commit_sha_new: null,
      synced_at: "2026-05-28T08:00:00Z",
    },
  ],
};

const DOCTOR_REPORT = {
  findings: [
    {
      id: { kind: "library_broken_symlink", path: "/Users/test/.tome/skills/orphan" },
      severity: "warning",
      category: "library",
      title: "Broken library symlink",
      description:
        "The symlink at /Users/test/.tome/skills/orphan points at a directory that no longer exists.",
      repair_kind: "remove_broken_library_symlink",
      dry_run_description:
        "Remove the broken symlink at /Users/test/.tome/skills/orphan.",
    },
    {
      id: {
        kind: "skill_unparsable_frontmatter",
        skill: "deprecated-skill",
      },
      severity: "blocked",
      category: "skill",
      title: "Unparsable SKILL.md frontmatter — deprecated-skill",
      description:
        "The YAML frontmatter delimiters are missing in /Users/test/skills/deprecated-skill/SKILL.md.",
      repair_kind: null,
      dry_run_description: null,
    },
  ],
  auto_fixable_count: 1,
  manual_count: 1,
};

/** Mocked invoke — switches on command name and returns the
 *  command's wrapped `Ok` payload (matching the `typedError` wrap that
 *  bindings.ts generates). */
export async function invoke(cmd: string, _args?: any): Promise<any> {
  switch (cmd) {
    case "get_status":
      return STATUS_REPORT;
    case "list_skills":
      return LIST_REPORT;
    case "get_skill_detail": {
      const name: string = _args?.name ?? "";
      return SKILL_DETAIL_BY_NAME[name] ?? SKILL_DETAIL_BY_NAME["axiom-build"];
    }
    case "set_skill_disabled":
      return null;
    case "open_source_folder":
      return null;
    case "copy_path":
      return "/Users/test/.claude/plugins/axiom-build";
    case "get_doctor_report":
      return DOCTOR_REPORT;
    case "doctor_repair_one":
      return null;
    // Phase 27 plan 27-01b — long-running sync pipeline commands.
    // The axe-core gate only scans the initial render tree; it never
    // exercises an actual sync. start_sync returns immediately with a
    // success unit so the SyncView's terminal-state placeholder renders
    // if the gate happens to click [Run sync]. cancel_sync is idempotent
    // on the Rust side and returns unit too.
    case "start_sync":
      return null;
    case "cancel_sync":
      return null;
    // Phase 27 plan 27-02 — SYNC-02 triage panel projection. The a11y gate
    // has two scans: the default empty-diff path (nothing renders besides
    // the idle hero) and a "triage" path that surfaces a representative
    // sample diff so axe can scan the GridList / sectioned headings /
    // RadioGroup composition. The triage path is selected by setting the
    // `?triage=1` query param on the loaded page.
    case "get_lockfile_diff":
      if (typeof window !== "undefined" && window.location?.search?.includes("triage=1")) {
        return TRIAGE_DIFF;
      }
      return { added: [], changed: [], removed: [] };
    // Phase 27 plan 27-03 — SYNC-03 Apply flow mocks. The a11y gate opens
    // the PreviewPopover by clicking [Apply N decisions], so the mock
    // returns a representative MachineTomlPreview the
    // MachineTomlDiff component renders inside the popover. Apply is a
    // no-op success that returns null — the popover closes and the
    // Sidebar badge clears.
    case "preview_machine_toml":
      return {
        lines: [
          { kind: "unchanged", line_number: 1, content: "[machine_prefs]" },
          { kind: "removed", line_number: 2, content: "disabled = []" },
          { kind: "added", line_number: 2, content: "disabled = [\"alpha\"]" },
        ],
        added_count: 1,
        removed_count: 1,
      };
    case "apply_machine_toml":
      return null;
    default:
      throw new Error(`a11y mock: unknown command '${cmd}'`);
  }
}

// Re-export the symbols `@tauri-apps/api/core` exposes that we touch.
export const transformCallback = (_cb: any) => 0;
export const Channel = class {
  onmessage: (() => void) | null = null;
};
