//! Safe Git coordination for the shared pool repository.
//!
//! This module intentionally owns a narrow Git surface: health preflight,
//! fast-forward pulls, the per-config-directory sync lock, and (later in this
//! phase) Tome-owned publication. It never repairs the caller's index.

use std::fs::OpenOptions;
use std::io::IsTerminal;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

use anyhow::{Context, Result};

use crate::profiles::GitSyncPolicy;

static NEXT_CONSENT_REQUEST: AtomicU64 = AtomicU64::new(1);

/// Rust-authoritative stage at which a shared-pool Git action needs consent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "bindings", derive(specta::Type))]
#[serde(rename_all = "snake_case")]
pub enum GitConsentStage {
    /// A fast-forward-only pull may update repository files.
    PrePull,
    /// A commit/push would publish the listed Tome-owned paths.
    PostSync,
}

/// A typed, server-issued request to choose a Git action.
///
/// The opaque `request_id` is generated by Rust and is only valid for the
/// continuation that produced this value. The webview renders this payload; it
/// never calculates paths, remote summaries, or policy.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
#[cfg_attr(feature = "bindings", derive(specta::Type))]
pub struct GitConsentRequired {
    pub request_id: String,
    pub stage: GitConsentStage,
    pub remote_summary: Option<String>,
    pub owned_changes: Vec<String>,
}

impl GitConsentRequired {
    fn pre_pull(remote_summary: String) -> Self {
        Self {
            request_id: next_request_id(),
            stage: GitConsentStage::PrePull,
            remote_summary: Some(remote_summary),
            owned_changes: Vec::new(),
        }
    }

    fn post_sync(owned_changes: Vec<String>) -> Self {
        Self {
            request_id: next_request_id(),
            stage: GitConsentStage::PostSync,
            remote_summary: None,
            owned_changes,
        }
    }
}

fn next_request_id() -> String {
    format!(
        "git-consent-{:016x}",
        NEXT_CONSENT_REQUEST.fetch_add(1, Ordering::Relaxed)
    )
}

/// A Rust-owned continuation waiting for one explicit Git decision.
pub struct PendingGitConsent {
    required: GitConsentRequired,
    session: RepoSync,
    operation: PendingGitOperation,
}

enum PendingGitOperation {
    Pull { upstream: String },
    Publish { changed: Vec<String> },
}

/// The noninteractive shared-pool Git boundary used by desktop callers.
pub enum RepoSyncStart {
    Ready(RepoSync),
    ConsentRequired(PendingGitConsent),
}

/// A decision forwarded verbatim from the UI for a server-issued request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Deserialize)]
#[cfg_attr(feature = "bindings", derive(specta::Type))]
#[serde(rename_all = "lowercase")]
pub enum GitConsentDecision {
    Accept,
    Decline,
}

/// Keeps a create-new config-directory lock alive for one sync invocation.
pub struct RepoSync {
    lock_path: PathBuf,
    repo_root: Option<PathBuf>,
}

impl PendingGitConsent {
    /// Return the immutable request payload associated with this continuation.
    pub fn required(&self) -> &GitConsentRequired {
        &self.required
    }

    /// Resume this exact continuation. Declining deliberately leaves the
    /// repository untouched and returns the still-locked local-only session.
    pub fn resume(self, decision: GitConsentDecision) -> Result<RepoSyncStart> {
        match self.operation {
            PendingGitOperation::Pull { upstream } => {
                if matches!(decision, GitConsentDecision::Accept) {
                    self.session.perform_pull(&upstream)?;
                }
                Ok(RepoSyncStart::Ready(self.session))
            }
            PendingGitOperation::Publish { changed } => {
                if matches!(decision, GitConsentDecision::Accept) {
                    self.session.commit_and_push(&changed)?;
                }
                Ok(RepoSyncStart::Ready(self.session))
            }
        }
    }
}

impl Drop for RepoSync {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.lock_path);
    }
}

impl RepoSync {
    /// Acquire the sync lock and perform any consented pre-reconciliation pull.
    pub(crate) fn begin(
        config_dir: &Path,
        policy: GitSyncPolicy,
        no_input: bool,
        dry_run: bool,
    ) -> Result<Self> {
        let lock_path = config_dir.join(".tome-sync.lock");
        let mut lock = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&lock_path)
            .with_context(|| {
                format!(
                    "another tome sync may be running: lock exists at {} (stale locks are never removed automatically)",
                    lock_path.display()
                )
            })?;
        use std::io::Write;
        if let Err(error) = writeln!(
            lock,
            "pid={} started_at={:?}",
            std::process::id(),
            std::time::SystemTime::now()
        ) {
            let _ = std::fs::remove_file(&lock_path);
            return Err(error)
                .with_context(|| format!("failed to write sync lock {}", lock_path.display()));
        }

        let repo_root = repository_root(config_dir)?;
        let session = Self {
            lock_path,
            repo_root,
        };
        session.pull_if_consented(policy, no_input, dry_run)?;
        Ok(session)
    }

    pub(crate) fn repo_root(&self) -> Option<&Path> {
        self.repo_root.as_deref()
    }

    /// Acquire the repository lock and return a typed pre-pull consent request
    /// for `git_sync = "ask"`. No terminal prompt is issued on this path.
    pub fn begin_for_desktop(
        config_dir: &Path,
        policy: GitSyncPolicy,
        dry_run: bool,
    ) -> Result<RepoSyncStart> {
        let lock_path = config_dir.join(".tome-sync.lock");
        let mut lock = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&lock_path)
            .with_context(|| {
                format!(
                    "another tome sync may be running: lock exists at {}",
                    lock_path.display()
                )
            })?;
        use std::io::Write;
        if let Err(error) = writeln!(
            lock,
            "pid={} started_at={:?}",
            std::process::id(),
            std::time::SystemTime::now()
        ) {
            let _ = std::fs::remove_file(&lock_path);
            return Err(error)
                .with_context(|| format!("failed to write sync lock {}", lock_path.display()));
        }
        let session = Self {
            lock_path,
            repo_root: repository_root(config_dir)?,
        };
        session.pre_pull_for_desktop(policy, dry_run)
    }

    /// After reconciliation, either publish immediately, request consent for
    /// the exact owned paths, or continue local-only.
    pub fn publish_for_desktop(
        self,
        paths: &crate::paths::TomePaths,
        policy: GitSyncPolicy,
    ) -> Result<RepoSyncStart> {
        if matches!(policy, GitSyncPolicy::Never) {
            return Ok(RepoSyncStart::Ready(self));
        }
        let Some(repo_root) = self.repo_root() else {
            return Ok(RepoSyncStart::Ready(self));
        };
        let status = status_snapshot(repo_root)?;
        if status.unsafe_reason().is_some() {
            return Ok(RepoSyncStart::Ready(self));
        }
        let owned = owned_paths(repo_root, paths)?;
        let changed = changed_owned_paths(repo_root, &owned)?;
        if changed.is_empty() {
            return Ok(RepoSyncStart::Ready(self));
        }
        match policy {
            GitSyncPolicy::Always => {
                self.commit_and_push(&changed)?;
                Ok(RepoSyncStart::Ready(self))
            }
            GitSyncPolicy::Ask => Ok(RepoSyncStart::ConsentRequired(PendingGitConsent {
                required: GitConsentRequired::post_sync(changed.clone()),
                session: self,
                operation: PendingGitOperation::Publish { changed },
            })),
            GitSyncPolicy::Never => Ok(RepoSyncStart::Ready(self)),
        }
    }

    fn pre_pull_for_desktop(self, policy: GitSyncPolicy, dry_run: bool) -> Result<RepoSyncStart> {
        if dry_run || matches!(policy, GitSyncPolicy::Never) {
            return Ok(RepoSyncStart::Ready(self));
        }
        let Some(repo_root) = self.repo_root() else {
            return Ok(RepoSyncStart::Ready(self));
        };
        let status = status_snapshot(repo_root)?;
        if status.unsafe_reason().is_some() {
            return Ok(RepoSyncStart::Ready(self));
        }
        let upstream = match git_stdout(
            repo_root,
            &[
                "rev-parse",
                "--abbrev-ref",
                "--symbolic-full-name",
                "@{upstream}",
            ],
        ) {
            Ok(upstream) => upstream,
            Err(_) => return Ok(RepoSyncStart::Ready(self)),
        };
        let summary = git_stdout(repo_root, &["fetch", "--dry-run", "--verbose"])
            .unwrap_or_else(|_| format!("updates from {upstream}"));
        match policy {
            GitSyncPolicy::Always => {
                self.perform_pull(&upstream)?;
                Ok(RepoSyncStart::Ready(self))
            }
            GitSyncPolicy::Ask => Ok(RepoSyncStart::ConsentRequired(PendingGitConsent {
                required: GitConsentRequired::pre_pull(
                    summary.lines().next().unwrap_or(&upstream).to_string(),
                ),
                session: self,
                operation: PendingGitOperation::Pull { upstream },
            })),
            GitSyncPolicy::Never => Ok(RepoSyncStart::Ready(self)),
        }
    }

    fn perform_pull(&self, upstream: &str) -> Result<()> {
        let Some(repo_root) = self.repo_root() else {
            return Ok(());
        };
        git_success(repo_root, &["fetch", "--prune"])?;
        let local = git_stdout(repo_root, &["rev-parse", "HEAD"])?;
        let remote = git_stdout(repo_root, &["rev-parse", upstream])?;
        if local != remote {
            git_success(repo_root, &["merge", "--ff-only", upstream])?;
        }
        Ok(())
    }

    fn commit_and_push(&self, changed: &[String]) -> Result<()> {
        let Some(repo_root) = self.repo_root() else {
            return Ok(());
        };
        let mut add_args = vec!["add", "--"];
        add_args.extend(changed.iter().map(String::as_str));
        git_success(repo_root, &add_args)?;
        git_success(
            repo_root,
            &["commit", "-m", "tome sync: update shared pool"],
        )?;
        if let Err(error) = git_success(repo_root, &["push"]) {
            eprintln!(
                "warning: git push failed; retained the local Tome commit for a later push: {error:#}"
            );
        }
        Ok(())
    }

    /// Commit and push only changed Tome-owned paths after reconciliation.
    /// A failed push deliberately retains the local commit for the next sync.
    pub(crate) fn publish(
        &self,
        paths: &crate::paths::TomePaths,
        policy: GitSyncPolicy,
        no_input: bool,
    ) -> Result<()> {
        if matches!(policy, GitSyncPolicy::Never) {
            return Ok(());
        }
        let Some(repo_root) = self.repo_root() else {
            return Ok(());
        };
        let status = status_snapshot(repo_root)?;
        if let Some(reason) = status.unsafe_reason() {
            eprintln!(
                "warning: managed Git publication is unavailable: {reason}; local changes were retained"
            );
            return Ok(());
        }
        let owned = match owned_paths(repo_root, paths) {
            Ok(owned) => owned,
            Err(error) => {
                eprintln!("warning: {error:#}; continuing local-only");
                return Ok(());
            }
        };
        let changed = changed_owned_paths(repo_root, &owned)?;
        if changed.is_empty() {
            if status.ahead > 0 {
                return self.push_if_consented(
                    repo_root,
                    policy,
                    no_input,
                    "existing Tome commits",
                );
            }
            return Ok(());
        }
        let summary = changed.join(", ");
        let approved = match policy {
            GitSyncPolicy::Always => true,
            GitSyncPolicy::Ask if no_input || !std::io::stdin().is_terminal() => {
                eprintln!(
                    "warning: git_sync = \"ask\" is noninteractive; local pool changes were not committed"
                );
                false
            }
            GitSyncPolicy::Ask => dialoguer::Confirm::new()
                .with_prompt(format!(
                    "Commit and push these Tome-owned changes? {summary}"
                ))
                .default(false)
                .interact()?,
            GitSyncPolicy::Never => false,
        };
        if !approved {
            return Ok(());
        }
        let mut add_args = vec!["add", "--"];
        add_args.extend(changed.iter().map(String::as_str));
        git_success(repo_root, &add_args)?;
        git_success(
            repo_root,
            &["commit", "-m", "tome sync: update shared pool"],
        )?;
        self.push_if_consented(repo_root, policy, no_input, "new Tome pool commit")
    }

    fn push_if_consented(
        &self,
        repo_root: &Path,
        policy: GitSyncPolicy,
        no_input: bool,
        description: &str,
    ) -> Result<()> {
        let approved = match policy {
            GitSyncPolicy::Always => true,
            GitSyncPolicy::Ask if no_input || !std::io::stdin().is_terminal() => false,
            GitSyncPolicy::Ask => dialoguer::Confirm::new()
                .with_prompt(format!("Push {description}?"))
                .default(false)
                .interact()?,
            GitSyncPolicy::Never => false,
        };
        if !approved {
            return Ok(());
        }
        if let Err(error) = git_success(repo_root, &["push"]) {
            eprintln!(
                "warning: git push failed; retained the local Tome commit for a later push: {error:#}"
            );
        }
        Ok(())
    }

    fn pull_if_consented(
        &self,
        policy: GitSyncPolicy,
        no_input: bool,
        dry_run: bool,
    ) -> Result<()> {
        if dry_run || matches!(policy, GitSyncPolicy::Never) {
            return Ok(());
        }
        let Some(repo_root) = self.repo_root() else {
            eprintln!(
                "warning: shared-pool Git coordination is unavailable outside a Git worktree; continuing local-only"
            );
            return Ok(());
        };
        let status = status_snapshot(repo_root)?;
        if let Some(reason) = status.unsafe_reason() {
            eprintln!("warning: managed Git pull is unavailable: {reason}; continuing local-only");
            return Ok(());
        }
        let upstream = match git_stdout(
            repo_root,
            &[
                "rev-parse",
                "--abbrev-ref",
                "--symbolic-full-name",
                "@{upstream}",
            ],
        ) {
            Ok(upstream) => upstream,
            Err(_) => {
                eprintln!(
                    "warning: shared-pool Git coordination needs an upstream branch; continuing local-only"
                );
                return Ok(());
            }
        };

        let should_pull = match policy {
            GitSyncPolicy::Always => true,
            GitSyncPolicy::Ask if no_input || !std::io::stdin().is_terminal() => {
                eprintln!(
                    "warning: git_sync = \"ask\" is noninteractive; continuing local-only (use --git-sync always to opt in)"
                );
                false
            }
            GitSyncPolicy::Ask => {
                let summary = git_stdout(repo_root, &["fetch", "--dry-run", "--verbose"])
                    .unwrap_or_else(|_| format!("updates from {upstream}"));
                dialoguer::Confirm::new()
                    .with_prompt(format!(
                        "Pull the shared repository fast-forward only? This may update unrelated repository files. Remote summary: {}",
                        summary.lines().next().unwrap_or(&upstream)
                    ))
                    .default(false)
                    .interact()?
            }
            GitSyncPolicy::Never => false,
        };
        if !should_pull {
            return Ok(());
        }

        git_success(repo_root, &["fetch", "--prune"])?;
        let local = git_stdout(repo_root, &["rev-parse", "HEAD"])?;
        let remote = git_stdout(repo_root, &["rev-parse", &upstream])?;
        if local != remote {
            git_success(repo_root, &["merge", "--ff-only", &upstream])?;
            println!(
                "  {} Pulled changes from remote",
                console::style("↓").cyan()
            );
        }
        Ok(())
    }
}

fn owned_paths(repo_root: &Path, paths: &crate::paths::TomePaths) -> Result<Vec<String>> {
    let mut owned = vec![
        repository_relative(repo_root, paths.library_dir())?,
        repository_relative(repo_root, &paths.config_path())?,
        repository_relative(repo_root, &paths.lockfile_path())?,
        repository_relative(repo_root, &paths.config_dir().join("machines"))?,
    ];
    owned.sort();
    owned.dedup();
    Ok(owned)
}

fn repository_relative(repo_root: &Path, path: &Path) -> Result<String> {
    let canonical_root = std::fs::canonicalize(repo_root).with_context(|| {
        format!(
            "failed to resolve repository worktree {}",
            repo_root.display()
        )
    })?;
    let canonical_path = std::fs::canonicalize(path).with_context(|| {
        format!(
            "failed to resolve Tome-owned path {} before Git publication",
            path.display()
        )
    })?;
    let relative = canonical_path.strip_prefix(&canonical_root).with_context(|| {
        format!(
            "shared-pool Git coordination is unavailable because Tome-owned path {} lies outside repository worktree {}",
            path.display(),
            repo_root.display()
        )
    })?;
    anyhow::ensure!(
        !relative.as_os_str().is_empty(),
        "repository root itself is not a valid Tome-owned Git path"
    );
    relative
        .to_str()
        .map(str::to_owned)
        .context("Tome-owned path is not valid UTF-8 for Git")
}

fn changed_owned_paths(repo_root: &Path, owned: &[String]) -> Result<Vec<String>> {
    let owned_refs: Vec<_> = owned.iter().map(String::as_str).collect();
    let mut diff_args = vec!["diff", "--name-only", "--"];
    diff_args.extend(owned_refs.iter().copied());
    let mut changed: Vec<String> = git_stdout(repo_root, &diff_args)?
        .lines()
        .filter(|line| !line.is_empty())
        .map(str::to_owned)
        .collect();
    let mut untracked_args = vec!["ls-files", "--others", "--exclude-standard", "--"];
    untracked_args.extend(owned_refs);
    changed.extend(
        git_stdout(repo_root, &untracked_args)?
            .lines()
            .filter(|line| !line.is_empty())
            .map(str::to_owned),
    );
    changed.sort();
    changed.dedup();
    Ok(changed)
}

#[derive(Debug, Clone, Default)]
pub(crate) struct ChangeSummary {
    pub total: usize,
    pub added: usize,
    pub modified: usize,
    pub deleted: usize,
}

#[derive(Debug, Clone, Default)]
pub(crate) struct StatusSnapshot {
    pub staged: ChangeSummary,
    pub unstaged: ChangeSummary,
    pub unmerged: bool,
    pub ahead: usize,
    pub behind: usize,
    pub detached: bool,
    pub upstream_available: bool,
    pub remote_available: bool,
    pub operation_in_progress: Option<String>,
    pub latest_commit_age_seconds: Option<u64>,
}

impl StatusSnapshot {
    fn unsafe_reason(&self) -> Option<&'static str> {
        if self.unmerged {
            Some("the repository has unresolved conflicts")
        } else if self.staged.total > 0 {
            Some("the repository has pre-existing staged changes")
        } else if self.operation_in_progress.is_some() {
            Some("a merge or rebase is in progress")
        } else if self.ahead > 0 && self.behind > 0 {
            Some("the branch has diverged from its upstream")
        } else if self.behind > 0 {
            Some("the branch is behind its upstream")
        } else {
            None
        }
    }
}

fn repository_root(config_dir: &Path) -> Result<Option<PathBuf>> {
    let output = match git(config_dir, &["rev-parse", "--show-toplevel"]) {
        Ok(output) => output,
        Err(error)
            if error
                .downcast_ref::<std::io::Error>()
                .is_some_and(|source| source.kind() == std::io::ErrorKind::NotFound) =>
        {
            return Ok(None);
        }
        Err(error) => return Err(error),
    };
    if !output.status.success() {
        return Ok(None);
    }
    Ok(Some(PathBuf::from(
        String::from_utf8_lossy(&output.stdout).trim(),
    )))
}

pub(crate) fn inspect_status(config_dir: &Path) -> Result<Option<StatusSnapshot>> {
    let Some(repo_root) = repository_root(config_dir)? else {
        return Ok(None);
    };
    status_snapshot(&repo_root).map(Some)
}

fn record_change(summary: &mut ChangeSummary, status: u8) {
    if status == b'.' || status == b' ' {
        return;
    }
    summary.total += 1;
    match status {
        b'A' | b'?' => summary.added += 1,
        b'D' => summary.deleted += 1,
        _ => summary.modified += 1,
    }
}

fn status_snapshot(repo_root: &Path) -> Result<StatusSnapshot> {
    let output = git(
        repo_root,
        &[
            "--no-optional-locks",
            "status",
            "--porcelain=v2",
            "--branch",
            "--show-stash",
        ],
    )?;
    if !output.status.success() {
        anyhow::bail!(
            "could not inspect Git repository health: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    let mut snapshot = parse_status_snapshot(&String::from_utf8_lossy(&output.stdout));
    let git_dir = git_stdout(repo_root, &["rev-parse", "--git-dir"])?;
    let git_dir = repo_root.join(git_dir);
    snapshot.operation_in_progress = if git_dir.join("MERGE_HEAD").exists() {
        Some("merge".to_string())
    } else if git_dir.join("rebase-merge").exists() || git_dir.join("rebase-apply").exists() {
        Some("rebase".to_string())
    } else {
        None
    };
    snapshot.remote_available = !git_stdout(repo_root, &["remote"])
        .unwrap_or_default()
        .is_empty();
    snapshot.latest_commit_age_seconds = git_stdout(repo_root, &["log", "-1", "--format=%ct"])
        .ok()
        .and_then(|timestamp| timestamp.parse::<u64>().ok())
        .and_then(|timestamp| {
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .ok()
                .map(|now| now.as_secs().saturating_sub(timestamp))
        });
    Ok(snapshot)
}

fn parse_status_snapshot(output: &str) -> StatusSnapshot {
    let mut snapshot = StatusSnapshot::default();
    for line in output.lines() {
        if let Some(ab) = line.strip_prefix("# branch.ab +") {
            let mut fields = ab.split(" -");
            snapshot.ahead = fields
                .next()
                .and_then(|value| value.parse().ok())
                .unwrap_or_default();
            snapshot.behind = fields
                .next()
                .and_then(|value| value.parse().ok())
                .unwrap_or_default();
        } else if let Some(head) = line.strip_prefix("# branch.head ") {
            snapshot.detached = head == "(detached)";
        } else if line.starts_with("# branch.upstream ") {
            snapshot.upstream_available = true;
        } else if line.starts_with("u ") {
            snapshot.unmerged = true;
        } else if line.starts_with("? ") {
            record_change(&mut snapshot.unstaged, b'?');
        } else if (line.starts_with("1 ") || line.starts_with("2 "))
            && let Some(xy) = line.split_whitespace().nth(1)
        {
            let bytes = xy.as_bytes();
            if bytes.len() >= 2 {
                record_change(&mut snapshot.staged, bytes[0]);
                record_change(&mut snapshot.unstaged, bytes[1]);
            }
        }
    }
    snapshot
}

fn git(repo_dir: &Path, args: &[&str]) -> Result<std::process::Output> {
    Command::new("git")
        .args(args)
        .current_dir(repo_dir)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .env_remove("GIT_INDEX_FILE")
        .output()
        .with_context(|| format!("failed to run git {}", args.join(" ")))
}

fn git_stdout(repo_dir: &Path, args: &[&str]) -> Result<String> {
    let output = git(repo_dir, args)?;
    if !output.status.success() {
        anyhow::bail!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn git_success(repo_dir: &Path, args: &[&str]) -> Result<()> {
    let output = git(repo_dir, args)?;
    if !output.status.success() {
        anyhow::bail!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn consent_requests_have_distinct_opaque_ids() {
        let first = GitConsentRequired::pre_pull("origin/main".to_string());
        let second = GitConsentRequired::pre_pull("origin/main".to_string());

        assert_ne!(first.request_id, second.request_id);
        assert_eq!(first.stage, GitConsentStage::PrePull);
        assert_eq!(first.remote_summary.as_deref(), Some("origin/main"));
        assert!(first.owned_changes.is_empty());
    }

    #[test]
    fn lock_is_create_new_and_released_on_drop() {
        let temp = tempfile::TempDir::new().unwrap();
        let first = RepoSync::begin(temp.path(), GitSyncPolicy::Never, true, false).unwrap();
        assert!(RepoSync::begin(temp.path(), GitSyncPolicy::Never, true, false).is_err());
        drop(first);
        assert!(RepoSync::begin(temp.path(), GitSyncPolicy::Never, true, false).is_ok());
    }

    #[test]
    fn unsafe_status_reasons_prioritize_index_and_history_protection() {
        assert_eq!(
            StatusSnapshot {
                staged: ChangeSummary {
                    total: 1,
                    ..Default::default()
                },
                ..Default::default()
            }
            .unsafe_reason(),
            Some("the repository has pre-existing staged changes")
        );
        assert_eq!(
            StatusSnapshot {
                behind: 1,
                ..Default::default()
            }
            .unsafe_reason(),
            Some("the branch is behind its upstream")
        );
        assert_eq!(
            StatusSnapshot {
                ahead: 1,
                behind: 1,
                ..Default::default()
            }
            .unsafe_reason(),
            Some("the branch has diverged from its upstream")
        );
    }

    #[test]
    fn porcelain_parser_projects_dirty_and_topology_states() {
        let snapshot = parse_status_snapshot(
            "# branch.oid abcdef\n\
             # branch.head main\n\
             # branch.upstream origin/main\n\
             # branch.ab +2 -3\n\
             1 AM N... 100644 100644 100644 abcdef abcdef staged-and-unstaged\n\
             1 .D N... 100644 100644 000000 abcdef abcdef deleted\n\
             ? untracked\n",
        );

        assert_eq!(snapshot.staged.total, 1);
        assert_eq!(snapshot.staged.added, 1);
        assert_eq!(snapshot.unstaged.total, 3);
        assert_eq!(snapshot.unstaged.added, 1);
        assert_eq!(snapshot.unstaged.deleted, 1);
        assert_eq!(snapshot.unstaged.modified, 1);
        assert_eq!(snapshot.ahead, 2);
        assert_eq!(snapshot.behind, 3);
        assert!(snapshot.upstream_available);
        assert!(!snapshot.detached);

        let detached = parse_status_snapshot("# branch.head (detached)\n");
        assert!(detached.detached);
        assert!(!detached.upstream_available);

        let conflicted =
            parse_status_snapshot("u UU N... 100644 100644 100644 100644 a b c conflict\n");
        assert!(conflicted.unmerged);
    }
}
